name: hmm
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.7*
  - numpy=1.21*
  - pandas=1.3*
  - ambermd::pytraj
  - pymol-open-source
  - jupyterlab=3*
  - matplotlib=3.4.2
  - scikit-learn=0.23.2
  - hmmlearn=0.2.8